properties.files=mail, crawler.core, crawler, pdf, check, intav, cacheintav, language, management, returnPaths, role, certificados, basic.service.default, basic.service, check.patterns

key.mail= mail.properties
file.mail=file:///app/properties/mail.properties

key.certificados= certificados.properties
file.certificados=file:///app/properties/certificados.properties

key.crawler.core= crawler.core.properties
file.crawler.core=file:///app/properties/crawler.core.properties

key.crawler=crawler.properties
file.crawler=file:///app/properties/crawler.properties

key.pdf=pdf.properties
file.pdf=file:///app/properties/pdf.properties

key.intav=intav.properties
file.intav=file:///app/properties/intav.properties

key.cacheintav=cacheintav.properties
file.cacheintav=file:///app/properties/cacheintav.properties

key.language=language.properties
file.language=file:///app/properties/language.properties

key.management=management.properties
file.management=file:///app/properties/management.properties

key.returnPaths=returnPaths.properties
file.returnPaths=file:///app/properties/returnPaths.properties

key.role=role.properties
file.role=file:///app/properties/role.properties

key.basic.service.default=basic.service.properties
file.basic.service.default=file:///app/properties/basic.service.default.properties

key.basic.service=basic.service.properties
file.basic.service=file:///app/properties/basic.service.properties

file.descriptions=file:///app/properties/check.descriptions.properties

key.check.patterns=check.patterns.properties
file.check.patterns=file:///app/properties/check.patterns.properties