services:
  oaw:
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      oawdb:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-XX:+UseShenandoahGC -XX:+UseNUMA -XX:-UseBiasedLocking -XX:ParallelGCThreads=2 -XX:+UseLargePages -Xms256M -Xmx2048M -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./files:/srv/files"

  oawdb:
    image: docker.io/mariadb:11.4
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./portal/scripts:/oaw/portal/scripts"
      - "oawdb:/var/lib/mysql"
    entrypoint: /bin/sh -c "
      set -eux && 
      find /oaw/portal/scripts -iname '*sql' | sort | grep -v 101_ROLLBACK_OAW_4.0.0.sql | xargs cat > /docker-entrypoint-initdb.d/init.sql &&
      exec /usr/local/bin/docker-entrypoint.sh mariadbd"
    environment:
      - MYSQL_ROOT_PASSWORD=oawdb
      - MYSQL_DATABASE=oawdb
      - MYSQL_USER=oawdb
      - MYSQL_PASSWORD=oawdb
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 60s
      retries: 3
      start_period: 60s      
      timeout: 10s
    restart: unless-stopped

  renderer:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    build: ./motor-js/renderer
    restart: unless-stopped
    
  proxy:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    build: ./motor-js/proxy      
    restart: unless-stopped

  nginx:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    build: ./motor-js/nginx
    links:
      - renderer
    restart: unless-stopped

  mailer:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    image: docker.io/axllent/mailpit
    ports:
      - "8025:8025"
    restart: unless-stopped
    command: -s 0.0.0.0:25

volumes:
  oawdb:
