version: '3.0'

services:
  node:
    image: artefactos-ic.scae.redsara.es:6001/oaw-wcagemtool:latest
    command: npm start
    restart: always
    container_name: wcag_em_tool_node

  nginx:
    image: artefactos-ic.scae.redsara.es:6000/nginx:1.13.8-alpine      
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf.conf:/etc/nginx/conf.d/default.conf
    links:
      - node
    restart: always
    shm_size: '1gb'
    container_name: wcag_em_tool_nginx
