version: '2.2'

services:
    renderer:
      privileged: true
      build: .
      image: oawjs_renderer
      ports:
        - "3005:3000"   
      cpus: 2
      restart: always
      command: node /opt/prerender/server.js
