version: '2.2'

services:

  renderer-1:
    privileged: true
    build: ../motor-js/renderer
    image: oawjs_renderer
    cpus: 2
    restart: always
    command: node /opt/prerender/server.js
    container_name: docker_renderer_1

  renderer-2:
    privileged: true
    build: ../motor-js/renderer
    image: oawjs_renderer
    cpus: 2
    restart: always
    command: node /opt/prerender/server.js
    container_name: docker_renderer_2

  renderer-3:
    privileged: true
    build: ../motor-js/renderer
    image: oawjs_renderer
    cpus: 2
    restart: always
    command: node /opt/prerender/server.js
    container_name: docker_renderer_3

  proxy:
    build: ../motor-js/proxy
    image: oawjs_proxy
    command: node /opt/proxy/index.js
    restart: always
    ports:
      - "18088:18088"
    container_name: oaw_proxy

  nginx:
    image: nginx:1.13.8-alpine
    volumes:
      - ../motor-js/nginx/reverse.conf:/etc/nginx/conf.d/default.conf
      - ../motor-js/nginx/certs/server.crt:/etc/nginx/ssl/server.crt
      - ../motor-js/nginx/certs/server.key:/etc/nginx/ssl/server.key
    links:
      - renderer-1
      - renderer-2
      - renderer-3
    restart: always
    shm_size: '1gb'
    container_name: oaw_nginx

  mysql:
    image: mysql:5.7.21
    command: --max_allowed_packet=32505856
    ports:
      - "55306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql"
      - "./mysql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql"
      - "./volumes/mysql/:/var/lib/mysql/"
    container_name: oaw_mysql

  tomcat:
    build: ./tomcat
    ports:
      - "18081:8080"
      - "18444:8443"
    volumes:
      - "../portal/target/oaw.war:/usr/local/tomcat/webapps/oaw.war"
      - "./tmp:/tmp"
    dns:
      - 192.168.4.9
      - 192.168.4.10
    links:
      - mysql
    restart: always
    container_name: oaw_tomcat
