networks:
  oaw-dev:
    driver: bridge
    name: oaw-dev
#solo para usar en windows
#volumes:
#  mysql_data:

services:

  renderer-1:
    privileged: true
    build: ../motor-js/renderer
    image: oawjs_renderer
    cpus: 2
    restart: always
    command: node /opt/prerender/server.js
    container_name: docker_oaw_renderer_1
    networks:
      - oaw-dev

  renderer-2:
    privileged: true
    build: ../motor-js/renderer
    image: oawjs_renderer
    cpus: 2
    restart: always
    command: node /opt/prerender/server.js
    container_name: docker_oaw_renderer_2
    networks:
      - oaw-dev

  renderer-3:
    privileged: true
    build: ../motor-js/renderer
    image: oawjs_renderer
    cpus: 2
    restart: always
    command: node /opt/prerender/server.js
    container_name: docker_oaw_renderer_3
    networks:
      - oaw-dev

  proxy:
    build: ../motor-js/proxy
    command: node /opt/proxy/index.js
    restart: always
    volumes:
      - ../motor-js/proxy/index.js:/opt/proxy/index.js
    container_name: oaw-dev-proxy
    ports:
      - 7013:7013
    networks:
      - oaw-dev

  nginx:
    #Este contenedor necesita certificados. Se autogeneran y renuevan sólos en el arranque del servicio
    #La variable CERT_DAYS especifica los días de vigencia del certificado
    #image: nginx:1.13.8-alpine
    build: ../motor-js/nginx
    volumes:
      #- ../motor-js/nginx/reverse.conf:/etc/nginx/conf.d/default.conf
      #- ../motor-js/nginx/certs/server.crt:/etc/nginx/ssl/server.crt
      #- ../motor-js/nginx/certs/server.key:/etc/nginx/ssl/server.key
      - ../motor-js/nginx/certs:/etc/nginx/ssl
    environment:
      # Duración de los certificados del nginx
      CERT_DAYS: 365

    links:
      - renderer-1
      - renderer-2
      - renderer-3
    restart: always
    shm_size: 1gb
    networks:
      - oaw-dev

  mysql:
    image: mysql:5.7.21
    command:
      --max_allowed_packet=32505856
      --innodb_use_native_aio=0
    ports:
      - 7012:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d/
      - ./volumes/mysql/:/var/lib/mysql/
       #- mysql_data:/var/lib/mysql #solo si se en un filesystem de windows
    container_name: oaw-dev-mysql
    restart: always
    networks:
      - oaw-dev
  
  oaw-tomcat:
    build: ./oaw-tomcat
    ports:
      - 7010:8080
      - 7011:8443
    volumes:
      - ../portal/target/oaw.war:/usr/local/tomcat/webapps/oaw.war
      - ./oaw-tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tmp:/tmp
      - ./oaw-properties:/app/properties/
    container_name: oaw-dev-tomcat
    depends_on:
      - mysql
    restart: always
    networks:
      - oaw-dev

  #Validador, es el motor que contiene las reglas de validación así como las APIs
  validador-tomcat:
    build: ./validador-tomcat
    ports:
      - 7014:8080
    volumes:
      - ../validador-oaw/target:/usr/local/tomcat/target
      - ../validador-oaw/config:/opt/usuarios/oaw-validador/config
    container_name: validador-tomcat
    restart: always
    depends_on:
      - oaw-tomcat
    networks:
      - oaw-dev
  
  #Servidor de correo para pruebas
  #Se configura en portal/profiles/docker/mail.properties
  maildev_oaw:
    image: maildev/maildev
    ports:
      - "1080:1080"  #exponemos sólo el puerto para acceder a la interfaz gráfica vía web
      #- "1025:1025"
    container_name: maildev_oaw 
    restart: always
    networks:
      - oaw-dev


