version: '2.2'

services:

    tomcat:
      build: ./tomcat  
      volumes:
        - "./tomcat/taw4_informes.war:/usr/local/tomcat/webapps/ROOT.war"
      dns:
        - 192.168.4.9
        - 192.168.4.10
      ports:
        - "18080:8080" 
        - "18443:8443"
        # JMX
        #- "19999:9999"
      cpus: 2
      links:
        - mysql
        - proxy
      container_name: tawdis_tomcat

    mysql:
      image: mysql:5.7.21
      command: --max_allowed_packet=32505856
      ports:
        - "13306:3306"      
      environment:
        MYSQL_ROOT_PASSWORD: root       
      volumes:
        - "./mysql/create_database_taw_estadisticas_2.0.0.sql:/docker-entrypoint-initdb.d/create_database_taw_estadisticas_2.0.0.sql"
        - "./volumes/mysql/:/var/lib/mysql/"
      container_name: tawdis_mysql

    renderer:
      privileged: true
      build: ./renderer
      scale: 3
      cpus: 2
      restart: always
      shm_size: '1gb'
      # command: node /opt/prerender/server.js
      command: node 
      

    proxy:
      build: ./proxy
      ports:
        - "18088:18088"         
      command: node /opt/proxy/index.js
      restart: always
      container_name: tawdis_proxy   

    nginx:
      image: nginx:1.13.8-alpine      
      volumes:
        - ./nginx/reverse.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/certs/server.crt:/etc/nginx/ssl/server.crt
        - ./nginx/certs/server.key:/etc/nginx/ssl/server.key        
      links:
        - mysql
        - renderer
      restart: always
      container_name: tawdis_nginx
